common:
   data_file: ./data/okvqa_test_2000.pt
   engines:
      - llava1.57b
      - llava1.513b
      - InstructBLIP7b
      - VisualGLM8b
      - MiniGPTV
model:
   model_hf: microsoft/DialogRPT-updown # microsoft/DialogRPT-updown EleutherAI/gpt-neo-125m
train:
   weight_decay: 0.001
   learning_rate: 0.00002
   batch_size: 2
   epoch_num: 5
   sckp_epoch: 1
   checkpoint_path: ./checkpoint

infer:
   engines:
      - llava1.57b
   infer_json: data/VQAv2_500.json
   checkpoint: checkpoint/2024030415_50_44_158278/Epoch1
   infer_result_dir: ./infer_result
   infer_result_file: infer
   device: cuda:0